name: SexPlugin
version: '${project.version}'
main: spectrum.sexplugin.SexPlugin
api-version: 1.19
commands:
  resettime:
    description: Reset timeOnServer param for player
    usage: /<command> <player>
    permission: sexplugin.hardcorereset
  showstats:
    description: Show statistics for player
    usage: /<command> <player>
    permission: sexplugin.hardcoreshowstats
  respawn:
    description: Respawn died player
    usage: /<command> <player>
    permission: sexplugin.hardcorerespawn