name: SexPlugin
version: '${project.version}'
main: spectrum.sexplugin.SexPlugin
api-version: 1.19
commands:
  sex-p-menu:
    description: Открыть меню выбора партиклов
    aliases:
      - sex-p-m
    usage: /<command>