name: SexPlugin
version: '${project.version}'
main: spectrum.sexplugin.SexPlugin
api-version: 1.19
commands:
  hardcore-stats-service-restart:
    usage:
      /hardcore-stats-service-restart
    aliases:
      - h-s-s-r
    description: Restarting hardcore service